Repository parkingkim/parkingkim-webapp, pull requests merged in 2024-02, with the labels that each got.

#19 feat: 주차장 정보를 담은 `Card` 컴포넌트를 구현한다.
  src/assets/index.ts
  src/assets/picture.svg
  src/assets/star-filled.svg
  src/assets/star.svg
  src/components/Map.tsx
  src/components/ParkingLotCard/Badge.tsx
  src/components/ParkingLotCard/index.tsx
  src/constants/index.ts
  src/hooks/useGeoLocation.ts
  src/index.css
  src/stories/Badge.stories.tsx
  src/stories/ParkingLotCard.stories.tsx
Labels: 기능구현🧱

#27 feat: 온보딩페이지 구현
  index.html
  package.json
  src/App.tsx
  src/assets/arrow_left.svg
  src/assets/arrow_top.svg
  src/assets/index.ts
  src/components/MobileView.tsx
  src/index.css
  src/main.tsx
  src/pages/Login/index.tsx
  src/pages/OnBoarding/components/Slide.tsx
  src/pages/OnBoarding/hooks/useOnBoardingContents.tsx
  src/pages/OnBoarding/index.tsx
  yarn.lock
Labels: 리팩터링🔨

#26 feat: `BottomSheet` 로직 변경
  src/components/BottomSheet/hook/useDraggable.tsx
  src/components/BottomSheet/index.tsx
  src/components/BottomTabBar.tsx
  src/components/Map.tsx
  src/components/SearchBar.tsx
  src/components/Text.tsx
  src/pages/home/components/InitialContent.tsx
  src/pages/home/components/SearchContent.tsx
  src/pages/home/components/SearchFilter.tsx
  src/pages/home/index.tsx
  src/theme.ts
Labels: 리팩터링🔨

#34 feat: 주차장 상세정보 페이지 구현
  src/App.css
  src/App.tsx
  src/assets/cash.svg
  src/assets/human.svg
  src/assets/index.ts
  src/assets/parking_type.svg
  src/assets/runner.svg
  src/components/BottomTabBar.tsx
  src/components/Map.tsx
  src/components/ReviewMenus.tsx
  src/index.css
  src/pages/ParkingLotDetail/components/Header.tsx
  src/pages/ParkingLotDetail/components/LeftoverParking.tsx
  src/pages/ParkingLotDetail/components/MainInfo.tsx
  src/pages/ParkingLotDetail/components/ParkingInfo.tsx
  src/pages/ParkingLotDetail/components/Review.tsx
  src/pages/ParkingLotDetail/index.tsx
  src/pages/home/components/InitialContent.tsx
  src/reset.css
Labels: 기능구현🧱

#37 fix: main 머지 과정에서 발생된 오류 수정
  .gitignore
  src/components/MobileView.tsx
  src/components/Text.tsx
  src/pages/home/components/InitialContent.tsx
  yarn.lock
Labels: 버그 수정💊
